#:schema node_modules/wrangler/config-schema.json
name = "your-cloudflare-project-name" # If you wanna try an actual deploy.
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
